feat: Add tests for docker with plugins (#160)
* feat: Add tests for docker with plugins

* Reduce test matrix for docker with plugins test

* Update api version lookup

* Show docker compose logs on failure

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -352,6 +352,71 @@ jobs:
 
           diff -u /tmp/latest.txt /tmp/actual.txt
 
+  EtherpadDockerWithPlugins:
+    name: Docker [${{ matrix.versions.tag }}] with plugins
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        versions: [
+          { tag: "2.7.2" },
+          { tag: "2.6.1" },
+          { tag: "2.5.0" },
+        ]
+      fail-fast: false
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v6
+
+      - name: Start docker containers
+        run: |
+          EP_VERSION=${{ matrix.versions.tag }} docker compose -f ./tests/e2e/docker/docker-compose.plugins.yml up -d --wait
+
+      - name: Dump docker compose logs on failure
+        if: failure()
+        run: |
+          docker compose -f ./tests/e2e/docker/docker-compose.plugins.yml logs --no-color --timestamps
+
+      - name: Cache Composer packages
+        id: composer-cache
+        uses: actions/cache@v5
+        with:
+          path: vendor
+          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-php-
+
+      - name: Install dependencies
+        run: composer install --prefer-dist --no-progress
+
+      - name: Scan etherpad instance
+        run: |
+          set -euo pipefail
+          output="$(bin/console.php ether:scan http://localhost:9001)"
+          echo "$output"
+
+          expected="Package version: ${{ matrix.versions.tag }}"
+          if ! grep -Fq "$expected" <<< "$output"; then
+            echo "Assertion failed: expected output to contain: $expected"
+            exit 1
+          fi
+
+          expectedPackages=(
+            "ep_align"
+            "ep_headings2"
+            "ep_font_color"
+            "ep_adminpads2"
+            "ep_comments_page"
+            "ep_font_size"
+            "ep_markdown"
+          )
+          for pkg in "${expectedPackages[@]}"; do
+            if ! grep -Fq "* $pkg" <<< "$output"; then
+            echo "Assertion failed: expected output to contain: * $pkg"
+            exit 1
+            fi
+          done
+
   EtherpadDifferentVersion:
     name: Docker [${{ matrix.versions.tag }}]
     runs-on: ubuntu-latest
